// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: irsa/v1/irsa.proto

package irsav1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/assistantx/backend/pkg/pb/irsa/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// IRSAServiceName is the fully-qualified name of the IRSAService service.
	IRSAServiceName = "irsa.v1.IRSAService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// IRSAServiceGetIRSAInfoProcedure is the fully-qualified name of the IRSAService's GetIRSAInfo RPC.
	IRSAServiceGetIRSAInfoProcedure = "/irsa.v1.IRSAService/GetIRSAInfo"
)

// IRSAServiceClient is a client for the irsa.v1.IRSAService service.
type IRSAServiceClient interface {
	GetIRSAInfo(context.Context, *connect.Request[v1.GetIRSAInfoRequest]) (*connect.Response[v1.IRSAInfo], error)
}

// NewIRSAServiceClient constructs a client for the irsa.v1.IRSAService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewIRSAServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) IRSAServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	iRSAServiceMethods := v1.File_irsa_v1_irsa_proto.Services().ByName("IRSAService").Methods()
	return &iRSAServiceClient{
		getIRSAInfo: connect.NewClient[v1.GetIRSAInfoRequest, v1.IRSAInfo](
			httpClient,
			baseURL+IRSAServiceGetIRSAInfoProcedure,
			connect.WithSchema(iRSAServiceMethods.ByName("GetIRSAInfo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// iRSAServiceClient implements IRSAServiceClient.
type iRSAServiceClient struct {
	getIRSAInfo *connect.Client[v1.GetIRSAInfoRequest, v1.IRSAInfo]
}

// GetIRSAInfo calls irsa.v1.IRSAService.GetIRSAInfo.
func (c *iRSAServiceClient) GetIRSAInfo(ctx context.Context, req *connect.Request[v1.GetIRSAInfoRequest]) (*connect.Response[v1.IRSAInfo], error) {
	return c.getIRSAInfo.CallUnary(ctx, req)
}

// IRSAServiceHandler is an implementation of the irsa.v1.IRSAService service.
type IRSAServiceHandler interface {
	GetIRSAInfo(context.Context, *connect.Request[v1.GetIRSAInfoRequest]) (*connect.Response[v1.IRSAInfo], error)
}

// NewIRSAServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewIRSAServiceHandler(svc IRSAServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	iRSAServiceMethods := v1.File_irsa_v1_irsa_proto.Services().ByName("IRSAService").Methods()
	iRSAServiceGetIRSAInfoHandler := connect.NewUnaryHandler(
		IRSAServiceGetIRSAInfoProcedure,
		svc.GetIRSAInfo,
		connect.WithSchema(iRSAServiceMethods.ByName("GetIRSAInfo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/irsa.v1.IRSAService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case IRSAServiceGetIRSAInfoProcedure:
			iRSAServiceGetIRSAInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedIRSAServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedIRSAServiceHandler struct{}

func (UnimplementedIRSAServiceHandler) GetIRSAInfo(context.Context, *connect.Request[v1.GetIRSAInfoRequest]) (*connect.Response[v1.IRSAInfo], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("irsa.v1.IRSAService.GetIRSAInfo is not implemented"))
}
