// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: livekit/v1/livekit.proto

package livekitv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/assistantx/backend/pkg/pb/livekit/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// LivekitServiceName is the fully-qualified name of the LivekitService service.
	LivekitServiceName = "livekit.v1.LivekitService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// LivekitServiceGetTokenProcedure is the fully-qualified name of the LivekitService's GetToken RPC.
	LivekitServiceGetTokenProcedure = "/livekit.v1.LivekitService/GetToken"
	// LivekitServiceGetSkillsProcedure is the fully-qualified name of the LivekitService's GetSkills
	// RPC.
	LivekitServiceGetSkillsProcedure = "/livekit.v1.LivekitService/GetSkills"
	// LivekitServiceGetDeviceSkillsProcedure is the fully-qualified name of the LivekitService's
	// GetDeviceSkills RPC.
	LivekitServiceGetDeviceSkillsProcedure = "/livekit.v1.LivekitService/GetDeviceSkills"
)

// LivekitServiceClient is a client for the livekit.v1.LivekitService service.
type LivekitServiceClient interface {
	// GetToken generates a LiveKit access token and dispatches an agent to the room.
	GetToken(context.Context, *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.GetTokenResponse], error)
	// GetSkills returns the default device skills configuration.
	GetSkills(context.Context, *connect.Request[v1.GetSkillsRequest]) (*connect.Response[v1.GetSkillsResponse], error)
	// GetDeviceSkills returns skills for a specific device type.
	GetDeviceSkills(context.Context, *connect.Request[v1.GetDeviceSkillsRequest]) (*connect.Response[v1.GetSkillsResponse], error)
}

// NewLivekitServiceClient constructs a client for the livekit.v1.LivekitService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewLivekitServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) LivekitServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	livekitServiceMethods := v1.File_livekit_v1_livekit_proto.Services().ByName("LivekitService").Methods()
	return &livekitServiceClient{
		getToken: connect.NewClient[v1.GetTokenRequest, v1.GetTokenResponse](
			httpClient,
			baseURL+LivekitServiceGetTokenProcedure,
			connect.WithSchema(livekitServiceMethods.ByName("GetToken")),
			connect.WithClientOptions(opts...),
		),
		getSkills: connect.NewClient[v1.GetSkillsRequest, v1.GetSkillsResponse](
			httpClient,
			baseURL+LivekitServiceGetSkillsProcedure,
			connect.WithSchema(livekitServiceMethods.ByName("GetSkills")),
			connect.WithClientOptions(opts...),
		),
		getDeviceSkills: connect.NewClient[v1.GetDeviceSkillsRequest, v1.GetSkillsResponse](
			httpClient,
			baseURL+LivekitServiceGetDeviceSkillsProcedure,
			connect.WithSchema(livekitServiceMethods.ByName("GetDeviceSkills")),
			connect.WithClientOptions(opts...),
		),
	}
}

// livekitServiceClient implements LivekitServiceClient.
type livekitServiceClient struct {
	getToken        *connect.Client[v1.GetTokenRequest, v1.GetTokenResponse]
	getSkills       *connect.Client[v1.GetSkillsRequest, v1.GetSkillsResponse]
	getDeviceSkills *connect.Client[v1.GetDeviceSkillsRequest, v1.GetSkillsResponse]
}

// GetToken calls livekit.v1.LivekitService.GetToken.
func (c *livekitServiceClient) GetToken(ctx context.Context, req *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.GetTokenResponse], error) {
	return c.getToken.CallUnary(ctx, req)
}

// GetSkills calls livekit.v1.LivekitService.GetSkills.
func (c *livekitServiceClient) GetSkills(ctx context.Context, req *connect.Request[v1.GetSkillsRequest]) (*connect.Response[v1.GetSkillsResponse], error) {
	return c.getSkills.CallUnary(ctx, req)
}

// GetDeviceSkills calls livekit.v1.LivekitService.GetDeviceSkills.
func (c *livekitServiceClient) GetDeviceSkills(ctx context.Context, req *connect.Request[v1.GetDeviceSkillsRequest]) (*connect.Response[v1.GetSkillsResponse], error) {
	return c.getDeviceSkills.CallUnary(ctx, req)
}

// LivekitServiceHandler is an implementation of the livekit.v1.LivekitService service.
type LivekitServiceHandler interface {
	// GetToken generates a LiveKit access token and dispatches an agent to the room.
	GetToken(context.Context, *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.GetTokenResponse], error)
	// GetSkills returns the default device skills configuration.
	GetSkills(context.Context, *connect.Request[v1.GetSkillsRequest]) (*connect.Response[v1.GetSkillsResponse], error)
	// GetDeviceSkills returns skills for a specific device type.
	GetDeviceSkills(context.Context, *connect.Request[v1.GetDeviceSkillsRequest]) (*connect.Response[v1.GetSkillsResponse], error)
}

// NewLivekitServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewLivekitServiceHandler(svc LivekitServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	livekitServiceMethods := v1.File_livekit_v1_livekit_proto.Services().ByName("LivekitService").Methods()
	livekitServiceGetTokenHandler := connect.NewUnaryHandler(
		LivekitServiceGetTokenProcedure,
		svc.GetToken,
		connect.WithSchema(livekitServiceMethods.ByName("GetToken")),
		connect.WithHandlerOptions(opts...),
	)
	livekitServiceGetSkillsHandler := connect.NewUnaryHandler(
		LivekitServiceGetSkillsProcedure,
		svc.GetSkills,
		connect.WithSchema(livekitServiceMethods.ByName("GetSkills")),
		connect.WithHandlerOptions(opts...),
	)
	livekitServiceGetDeviceSkillsHandler := connect.NewUnaryHandler(
		LivekitServiceGetDeviceSkillsProcedure,
		svc.GetDeviceSkills,
		connect.WithSchema(livekitServiceMethods.ByName("GetDeviceSkills")),
		connect.WithHandlerOptions(opts...),
	)
	return "/livekit.v1.LivekitService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case LivekitServiceGetTokenProcedure:
			livekitServiceGetTokenHandler.ServeHTTP(w, r)
		case LivekitServiceGetSkillsProcedure:
			livekitServiceGetSkillsHandler.ServeHTTP(w, r)
		case LivekitServiceGetDeviceSkillsProcedure:
			livekitServiceGetDeviceSkillsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedLivekitServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedLivekitServiceHandler struct{}

func (UnimplementedLivekitServiceHandler) GetToken(context.Context, *connect.Request[v1.GetTokenRequest]) (*connect.Response[v1.GetTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("livekit.v1.LivekitService.GetToken is not implemented"))
}

func (UnimplementedLivekitServiceHandler) GetSkills(context.Context, *connect.Request[v1.GetSkillsRequest]) (*connect.Response[v1.GetSkillsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("livekit.v1.LivekitService.GetSkills is not implemented"))
}

func (UnimplementedLivekitServiceHandler) GetDeviceSkills(context.Context, *connect.Request[v1.GetDeviceSkillsRequest]) (*connect.Response[v1.GetSkillsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("livekit.v1.LivekitService.GetDeviceSkills is not implemented"))
}
