// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: auth/v1/auth.proto

package authv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/assistantx/backend/pkg/pb/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "auth.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceGetUserInfoProcedure is the fully-qualified name of the AuthService's GetUserInfo RPC.
	AuthServiceGetUserInfoProcedure = "/auth.v1.AuthService/GetUserInfo"
	// AuthServiceAuthorizeProcedure is the fully-qualified name of the AuthService's Authorize RPC.
	AuthServiceAuthorizeProcedure = "/auth.v1.AuthService/Authorize"
	// AuthServiceTokenProcedure is the fully-qualified name of the AuthService's Token RPC.
	AuthServiceTokenProcedure = "/auth.v1.AuthService/Token"
	// AuthServiceLogoutProcedure is the fully-qualified name of the AuthService's Logout RPC.
	AuthServiceLogoutProcedure = "/auth.v1.AuthService/Logout"
)

// AuthServiceClient is a client for the auth.v1.AuthService service.
type AuthServiceClient interface {
	// GetUserInfo validates the Authorization Bearer token and returns user claims.
	// Returns UNAUTHENTICATED (code 16) if token is invalid or expired.
	GetUserInfo(context.Context, *connect.Request[v1.GetUserInfoRequest]) (*connect.Response[v1.UserInfo], error)
	// Authorize returns an OIDC authorization URL for PKCE flow.
	Authorize(context.Context, *connect.Request[v1.AuthorizeRequest]) (*connect.Response[v1.AuthorizeResponse], error)
	// Token exchanges an authorization code for tokens, or refreshes an existing token.
	Token(context.Context, *connect.Request[v1.TokenRequest]) (*connect.Response[v1.TokenResponse], error)
	// Logout returns an OIDC end_session_endpoint URL for the client to redirect to.
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
}

// NewAuthServiceClient constructs a client for the auth.v1.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		getUserInfo: connect.NewClient[v1.GetUserInfoRequest, v1.UserInfo](
			httpClient,
			baseURL+AuthServiceGetUserInfoProcedure,
			connect.WithSchema(authServiceMethods.ByName("GetUserInfo")),
			connect.WithClientOptions(opts...),
		),
		authorize: connect.NewClient[v1.AuthorizeRequest, v1.AuthorizeResponse](
			httpClient,
			baseURL+AuthServiceAuthorizeProcedure,
			connect.WithSchema(authServiceMethods.ByName("Authorize")),
			connect.WithClientOptions(opts...),
		),
		token: connect.NewClient[v1.TokenRequest, v1.TokenResponse](
			httpClient,
			baseURL+AuthServiceTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("Token")),
			connect.WithClientOptions(opts...),
		),
		logout: connect.NewClient[v1.LogoutRequest, v1.LogoutResponse](
			httpClient,
			baseURL+AuthServiceLogoutProcedure,
			connect.WithSchema(authServiceMethods.ByName("Logout")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	getUserInfo *connect.Client[v1.GetUserInfoRequest, v1.UserInfo]
	authorize   *connect.Client[v1.AuthorizeRequest, v1.AuthorizeResponse]
	token       *connect.Client[v1.TokenRequest, v1.TokenResponse]
	logout      *connect.Client[v1.LogoutRequest, v1.LogoutResponse]
}

// GetUserInfo calls auth.v1.AuthService.GetUserInfo.
func (c *authServiceClient) GetUserInfo(ctx context.Context, req *connect.Request[v1.GetUserInfoRequest]) (*connect.Response[v1.UserInfo], error) {
	return c.getUserInfo.CallUnary(ctx, req)
}

// Authorize calls auth.v1.AuthService.Authorize.
func (c *authServiceClient) Authorize(ctx context.Context, req *connect.Request[v1.AuthorizeRequest]) (*connect.Response[v1.AuthorizeResponse], error) {
	return c.authorize.CallUnary(ctx, req)
}

// Token calls auth.v1.AuthService.Token.
func (c *authServiceClient) Token(ctx context.Context, req *connect.Request[v1.TokenRequest]) (*connect.Response[v1.TokenResponse], error) {
	return c.token.CallUnary(ctx, req)
}

// Logout calls auth.v1.AuthService.Logout.
func (c *authServiceClient) Logout(ctx context.Context, req *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return c.logout.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the auth.v1.AuthService service.
type AuthServiceHandler interface {
	// GetUserInfo validates the Authorization Bearer token and returns user claims.
	// Returns UNAUTHENTICATED (code 16) if token is invalid or expired.
	GetUserInfo(context.Context, *connect.Request[v1.GetUserInfoRequest]) (*connect.Response[v1.UserInfo], error)
	// Authorize returns an OIDC authorization URL for PKCE flow.
	Authorize(context.Context, *connect.Request[v1.AuthorizeRequest]) (*connect.Response[v1.AuthorizeResponse], error)
	// Token exchanges an authorization code for tokens, or refreshes an existing token.
	Token(context.Context, *connect.Request[v1.TokenRequest]) (*connect.Response[v1.TokenResponse], error)
	// Logout returns an OIDC end_session_endpoint URL for the client to redirect to.
	Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceGetUserInfoHandler := connect.NewUnaryHandler(
		AuthServiceGetUserInfoProcedure,
		svc.GetUserInfo,
		connect.WithSchema(authServiceMethods.ByName("GetUserInfo")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceAuthorizeHandler := connect.NewUnaryHandler(
		AuthServiceAuthorizeProcedure,
		svc.Authorize,
		connect.WithSchema(authServiceMethods.ByName("Authorize")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceTokenHandler := connect.NewUnaryHandler(
		AuthServiceTokenProcedure,
		svc.Token,
		connect.WithSchema(authServiceMethods.ByName("Token")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLogoutHandler := connect.NewUnaryHandler(
		AuthServiceLogoutProcedure,
		svc.Logout,
		connect.WithSchema(authServiceMethods.ByName("Logout")),
		connect.WithHandlerOptions(opts...),
	)
	return "/auth.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceGetUserInfoProcedure:
			authServiceGetUserInfoHandler.ServeHTTP(w, r)
		case AuthServiceAuthorizeProcedure:
			authServiceAuthorizeHandler.ServeHTTP(w, r)
		case AuthServiceTokenProcedure:
			authServiceTokenHandler.ServeHTTP(w, r)
		case AuthServiceLogoutProcedure:
			authServiceLogoutHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) GetUserInfo(context.Context, *connect.Request[v1.GetUserInfoRequest]) (*connect.Response[v1.UserInfo], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.GetUserInfo is not implemented"))
}

func (UnimplementedAuthServiceHandler) Authorize(context.Context, *connect.Request[v1.AuthorizeRequest]) (*connect.Response[v1.AuthorizeResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.Authorize is not implemented"))
}

func (UnimplementedAuthServiceHandler) Token(context.Context, *connect.Request[v1.TokenRequest]) (*connect.Response[v1.TokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.Token is not implemented"))
}

func (UnimplementedAuthServiceHandler) Logout(context.Context, *connect.Request[v1.LogoutRequest]) (*connect.Response[v1.LogoutResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.Logout is not implemented"))
}
