// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: livekit/v1/livekit.proto

package livekitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Scene         string                 `protobuf:"bytes,2,opt,name=scene,proto3" json:"scene,omitempty"` // Scene type: "car", "home", "charger"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_livekit_v1_livekit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_v1_livekit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_livekit_v1_livekit_proto_rawDescGZIP(), []int{0}
}

func (x *GetTokenRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *GetTokenRequest) GetScene() string {
	if x != nil {
		return x.Scene
	}
	return ""
}

type GetTokenResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ServerUrl        string                 `protobuf:"bytes,1,opt,name=server_url,json=serverUrl,proto3" json:"server_url,omitempty"`
	ParticipantToken string                 `protobuf:"bytes,2,opt,name=participant_token,json=participantToken,proto3" json:"participant_token,omitempty"`
	Token            string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"` // Alias for compatibility
	RoomName         string                 `protobuf:"bytes,4,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Identity         string                 `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	Name             string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_livekit_v1_livekit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_v1_livekit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_livekit_v1_livekit_proto_rawDescGZIP(), []int{1}
}

func (x *GetTokenResponse) GetServerUrl() string {
	if x != nil {
		return x.ServerUrl
	}
	return ""
}

func (x *GetTokenResponse) GetParticipantToken() string {
	if x != nil {
		return x.ParticipantToken
	}
	return ""
}

func (x *GetTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetTokenResponse) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *GetTokenResponse) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *GetTokenResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillsRequest) Reset() {
	*x = GetSkillsRequest{}
	mi := &file_livekit_v1_livekit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillsRequest) ProtoMessage() {}

func (x *GetSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_v1_livekit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillsRequest.ProtoReflect.Descriptor instead.
func (*GetSkillsRequest) Descriptor() ([]byte, []int) {
	return file_livekit_v1_livekit_proto_rawDescGZIP(), []int{2}
}

type GetDeviceSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceSkillsRequest) Reset() {
	*x = GetDeviceSkillsRequest{}
	mi := &file_livekit_v1_livekit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceSkillsRequest) ProtoMessage() {}

func (x *GetDeviceSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_v1_livekit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceSkillsRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceSkillsRequest) Descriptor() ([]byte, []int) {
	return file_livekit_v1_livekit_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeviceSkillsRequest) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

type GetSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *structpb.Struct       `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSkillsResponse) Reset() {
	*x = GetSkillsResponse{}
	mi := &file_livekit_v1_livekit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSkillsResponse) ProtoMessage() {}

func (x *GetSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_livekit_v1_livekit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSkillsResponse.ProtoReflect.Descriptor instead.
func (*GetSkillsResponse) Descriptor() ([]byte, []int) {
	return file_livekit_v1_livekit_proto_rawDescGZIP(), []int{4}
}

func (x *GetSkillsResponse) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_livekit_v1_livekit_proto protoreflect.FileDescriptor

const file_livekit_v1_livekit_proto_rawDesc = "" +
	"\n" +
	"\x18livekit/v1/livekit.proto\x12\n" +
	"livekit.v1\x1a\x1cgoogle/protobuf/struct.proto\"D\n" +
	"\x0fGetTokenRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x14\n" +
	"\x05scene\x18\x02 \x01(\tR\x05scene\"\xc1\x01\n" +
	"\x10GetTokenResponse\x12\x1d\n" +
	"\n" +
	"server_url\x18\x01 \x01(\tR\tserverUrl\x12+\n" +
	"\x11participant_token\x18\x02 \x01(\tR\x10participantToken\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12\x1b\n" +
	"\troom_name\x18\x04 \x01(\tR\broomName\x12\x1a\n" +
	"\bidentity\x18\x05 \x01(\tR\bidentity\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\"\x12\n" +
	"\x10GetSkillsRequest\"0\n" +
	"\x16GetDeviceSkillsRequest\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\"@\n" +
	"\x11GetSkillsResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.google.protobuf.StructR\x04data2\xf7\x01\n" +
	"\x0eLivekitService\x12E\n" +
	"\bGetToken\x12\x1b.livekit.v1.GetTokenRequest\x1a\x1c.livekit.v1.GetTokenResponse\x12H\n" +
	"\tGetSkills\x12\x1c.livekit.v1.GetSkillsRequest\x1a\x1d.livekit.v1.GetSkillsResponse\x12T\n" +
	"\x0fGetDeviceSkills\x12\".livekit.v1.GetDeviceSkillsRequest\x1a\x1d.livekit.v1.GetSkillsResponseB\xa2\x01\n" +
	"\x0ecom.livekit.v1B\fLivekitProtoP\x01Z9github.com/assistantx/backend/pkg/pb/livekit/v1;livekitv1\xa2\x02\x03LXX\xaa\x02\n" +
	"Livekit.V1\xca\x02\n" +
	"Livekit\\V1\xe2\x02\x16Livekit\\V1\\GPBMetadata\xea\x02\vLivekit::V1b\x06proto3"

var (
	file_livekit_v1_livekit_proto_rawDescOnce sync.Once
	file_livekit_v1_livekit_proto_rawDescData []byte
)

func file_livekit_v1_livekit_proto_rawDescGZIP() []byte {
	file_livekit_v1_livekit_proto_rawDescOnce.Do(func() {
		file_livekit_v1_livekit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_livekit_v1_livekit_proto_rawDesc), len(file_livekit_v1_livekit_proto_rawDesc)))
	})
	return file_livekit_v1_livekit_proto_rawDescData
}

var file_livekit_v1_livekit_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_livekit_v1_livekit_proto_goTypes = []any{
	(*GetTokenRequest)(nil),        // 0: livekit.v1.GetTokenRequest
	(*GetTokenResponse)(nil),       // 1: livekit.v1.GetTokenResponse
	(*GetSkillsRequest)(nil),       // 2: livekit.v1.GetSkillsRequest
	(*GetDeviceSkillsRequest)(nil), // 3: livekit.v1.GetDeviceSkillsRequest
	(*GetSkillsResponse)(nil),      // 4: livekit.v1.GetSkillsResponse
	(*structpb.Struct)(nil),        // 5: google.protobuf.Struct
}
var file_livekit_v1_livekit_proto_depIdxs = []int32{
	5, // 0: livekit.v1.GetSkillsResponse.data:type_name -> google.protobuf.Struct
	0, // 1: livekit.v1.LivekitService.GetToken:input_type -> livekit.v1.GetTokenRequest
	2, // 2: livekit.v1.LivekitService.GetSkills:input_type -> livekit.v1.GetSkillsRequest
	3, // 3: livekit.v1.LivekitService.GetDeviceSkills:input_type -> livekit.v1.GetDeviceSkillsRequest
	1, // 4: livekit.v1.LivekitService.GetToken:output_type -> livekit.v1.GetTokenResponse
	4, // 5: livekit.v1.LivekitService.GetSkills:output_type -> livekit.v1.GetSkillsResponse
	4, // 6: livekit.v1.LivekitService.GetDeviceSkills:output_type -> livekit.v1.GetSkillsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_livekit_v1_livekit_proto_init() }
func file_livekit_v1_livekit_proto_init() {
	if File_livekit_v1_livekit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_livekit_v1_livekit_proto_rawDesc), len(file_livekit_v1_livekit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_livekit_v1_livekit_proto_goTypes,
		DependencyIndexes: file_livekit_v1_livekit_proto_depIdxs,
		MessageInfos:      file_livekit_v1_livekit_proto_msgTypes,
	}.Build()
	File_livekit_v1_livekit_proto = out.File
	file_livekit_v1_livekit_proto_goTypes = nil
	file_livekit_v1_livekit_proto_depIdxs = nil
}
