name: Deploy Helm to EKS

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  # Set the repository variable AWS_ACCOUNT_ID (Settings → Secrets and variables → Actions → Variables).
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: us-west-2
  EKS_CLUSTER: xorbit

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
      with:
        role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy Helm to Amazon EKS
      uses: bitovi/github-actions-deploy-eks-helm@29f556cf128eb1b42f834caf13b60a630ee2a20b # v1.2.12
      with:
        aws-region: ${{ env.AWS_REGION }}
        cluster-name: ${{ env.EKS_CLUSTER }}
        chart-path: charts/
        namespace: scaffolding
        name: app
