// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: irsa/v1/irsa.proto

package irsav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIRSAInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIRSAInfoRequest) Reset() {
	*x = GetIRSAInfoRequest{}
	mi := &file_irsa_v1_irsa_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIRSAInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIRSAInfoRequest) ProtoMessage() {}

func (x *GetIRSAInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_irsa_v1_irsa_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIRSAInfoRequest.ProtoReflect.Descriptor instead.
func (*GetIRSAInfoRequest) Descriptor() ([]byte, []int) {
	return file_irsa_v1_irsa_proto_rawDescGZIP(), []int{0}
}

type CallerIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Arn           string                 `protobuf:"bytes,3,opt,name=arn,proto3" json:"arn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallerIdentity) Reset() {
	*x = CallerIdentity{}
	mi := &file_irsa_v1_irsa_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallerIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallerIdentity) ProtoMessage() {}

func (x *CallerIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_irsa_v1_irsa_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallerIdentity.ProtoReflect.Descriptor instead.
func (*CallerIdentity) Descriptor() ([]byte, []int) {
	return file_irsa_v1_irsa_proto_rawDescGZIP(), []int{1}
}

func (x *CallerIdentity) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *CallerIdentity) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CallerIdentity) GetArn() string {
	if x != nil {
		return x.Arn
	}
	return ""
}

type RoleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleName      string                 `protobuf:"bytes,1,opt,name=role_name,json=roleName,proto3" json:"role_name,omitempty"`
	RoleArn       string                 `protobuf:"bytes,2,opt,name=role_arn,json=roleArn,proto3" json:"role_arn,omitempty"`
	RoleId        string                 `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	CreateDate    string                 `protobuf:"bytes,5,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleInfo) Reset() {
	*x = RoleInfo{}
	mi := &file_irsa_v1_irsa_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleInfo) ProtoMessage() {}

func (x *RoleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_irsa_v1_irsa_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleInfo.ProtoReflect.Descriptor instead.
func (*RoleInfo) Descriptor() ([]byte, []int) {
	return file_irsa_v1_irsa_proto_rawDescGZIP(), []int{2}
}

func (x *RoleInfo) GetRoleName() string {
	if x != nil {
		return x.RoleName
	}
	return ""
}

func (x *RoleInfo) GetRoleArn() string {
	if x != nil {
		return x.RoleArn
	}
	return ""
}

func (x *RoleInfo) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *RoleInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoleInfo) GetCreateDate() string {
	if x != nil {
		return x.CreateDate
	}
	return ""
}

type PolicyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyName    string                 `protobuf:"bytes,1,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	PolicyArn     string                 `protobuf:"bytes,2,opt,name=policy_arn,json=policyArn,proto3" json:"policy_arn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyInfo) Reset() {
	*x = PolicyInfo{}
	mi := &file_irsa_v1_irsa_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyInfo) ProtoMessage() {}

func (x *PolicyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_irsa_v1_irsa_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyInfo.ProtoReflect.Descriptor instead.
func (*PolicyInfo) Descriptor() ([]byte, []int) {
	return file_irsa_v1_irsa_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyInfo) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *PolicyInfo) GetPolicyArn() string {
	if x != nil {
		return x.PolicyArn
	}
	return ""
}

type IRSAInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CallerIdentity    *CallerIdentity        `protobuf:"bytes,1,opt,name=caller_identity,json=callerIdentity,proto3" json:"caller_identity,omitempty"`
	RoleInfo          *RoleInfo              `protobuf:"bytes,2,opt,name=role_info,json=roleInfo,proto3" json:"role_info,omitempty"`
	AttachedPolicies  []*PolicyInfo          `protobuf:"bytes,3,rep,name=attached_policies,json=attachedPolicies,proto3" json:"attached_policies,omitempty"`
	InlinePolicyNames []string               `protobuf:"bytes,4,rep,name=inline_policy_names,json=inlinePolicyNames,proto3" json:"inline_policy_names,omitempty"`
	Error             string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *IRSAInfo) Reset() {
	*x = IRSAInfo{}
	mi := &file_irsa_v1_irsa_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IRSAInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IRSAInfo) ProtoMessage() {}

func (x *IRSAInfo) ProtoReflect() protoreflect.Message {
	mi := &file_irsa_v1_irsa_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IRSAInfo.ProtoReflect.Descriptor instead.
func (*IRSAInfo) Descriptor() ([]byte, []int) {
	return file_irsa_v1_irsa_proto_rawDescGZIP(), []int{4}
}

func (x *IRSAInfo) GetCallerIdentity() *CallerIdentity {
	if x != nil {
		return x.CallerIdentity
	}
	return nil
}

func (x *IRSAInfo) GetRoleInfo() *RoleInfo {
	if x != nil {
		return x.RoleInfo
	}
	return nil
}

func (x *IRSAInfo) GetAttachedPolicies() []*PolicyInfo {
	if x != nil {
		return x.AttachedPolicies
	}
	return nil
}

func (x *IRSAInfo) GetInlinePolicyNames() []string {
	if x != nil {
		return x.InlinePolicyNames
	}
	return nil
}

func (x *IRSAInfo) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_irsa_v1_irsa_proto protoreflect.FileDescriptor

const file_irsa_v1_irsa_proto_rawDesc = "" +
	"\n" +
	"\x12irsa/v1/irsa.proto\x12\airsa.v1\"\x14\n" +
	"\x12GetIRSAInfoRequest\"U\n" +
	"\x0eCallerIdentity\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03arn\x18\x03 \x01(\tR\x03arn\"\x9e\x01\n" +
	"\bRoleInfo\x12\x1b\n" +
	"\trole_name\x18\x01 \x01(\tR\broleName\x12\x19\n" +
	"\brole_arn\x18\x02 \x01(\tR\aroleArn\x12\x17\n" +
	"\arole_id\x18\x03 \x01(\tR\x06roleId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcreate_date\x18\x05 \x01(\tR\n" +
	"createDate\"L\n" +
	"\n" +
	"PolicyInfo\x12\x1f\n" +
	"\vpolicy_name\x18\x01 \x01(\tR\n" +
	"policyName\x12\x1d\n" +
	"\n" +
	"policy_arn\x18\x02 \x01(\tR\tpolicyArn\"\x84\x02\n" +
	"\bIRSAInfo\x12@\n" +
	"\x0fcaller_identity\x18\x01 \x01(\v2\x17.irsa.v1.CallerIdentityR\x0ecallerIdentity\x12.\n" +
	"\trole_info\x18\x02 \x01(\v2\x11.irsa.v1.RoleInfoR\broleInfo\x12@\n" +
	"\x11attached_policies\x18\x03 \x03(\v2\x13.irsa.v1.PolicyInfoR\x10attachedPolicies\x12.\n" +
	"\x13inline_policy_names\x18\x04 \x03(\tR\x11inlinePolicyNames\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error2L\n" +
	"\vIRSAService\x12=\n" +
	"\vGetIRSAInfo\x12\x1b.irsa.v1.GetIRSAInfoRequest\x1a\x11.irsa.v1.IRSAInfoB\x8a\x01\n" +
	"\vcom.irsa.v1B\tIrsaProtoP\x01Z3github.com/assistantx/backend/pkg/pb/irsa/v1;irsav1\xa2\x02\x03IXX\xaa\x02\aIrsa.V1\xca\x02\aIrsa\\V1\xe2\x02\x13Irsa\\V1\\GPBMetadata\xea\x02\bIrsa::V1b\x06proto3"

var (
	file_irsa_v1_irsa_proto_rawDescOnce sync.Once
	file_irsa_v1_irsa_proto_rawDescData []byte
)

func file_irsa_v1_irsa_proto_rawDescGZIP() []byte {
	file_irsa_v1_irsa_proto_rawDescOnce.Do(func() {
		file_irsa_v1_irsa_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_irsa_v1_irsa_proto_rawDesc), len(file_irsa_v1_irsa_proto_rawDesc)))
	})
	return file_irsa_v1_irsa_proto_rawDescData
}

var file_irsa_v1_irsa_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_irsa_v1_irsa_proto_goTypes = []any{
	(*GetIRSAInfoRequest)(nil), // 0: irsa.v1.GetIRSAInfoRequest
	(*CallerIdentity)(nil),     // 1: irsa.v1.CallerIdentity
	(*RoleInfo)(nil),           // 2: irsa.v1.RoleInfo
	(*PolicyInfo)(nil),         // 3: irsa.v1.PolicyInfo
	(*IRSAInfo)(nil),           // 4: irsa.v1.IRSAInfo
}
var file_irsa_v1_irsa_proto_depIdxs = []int32{
	1, // 0: irsa.v1.IRSAInfo.caller_identity:type_name -> irsa.v1.CallerIdentity
	2, // 1: irsa.v1.IRSAInfo.role_info:type_name -> irsa.v1.RoleInfo
	3, // 2: irsa.v1.IRSAInfo.attached_policies:type_name -> irsa.v1.PolicyInfo
	0, // 3: irsa.v1.IRSAService.GetIRSAInfo:input_type -> irsa.v1.GetIRSAInfoRequest
	4, // 4: irsa.v1.IRSAService.GetIRSAInfo:output_type -> irsa.v1.IRSAInfo
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_irsa_v1_irsa_proto_init() }
func file_irsa_v1_irsa_proto_init() {
	if File_irsa_v1_irsa_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_irsa_v1_irsa_proto_rawDesc), len(file_irsa_v1_irsa_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_irsa_v1_irsa_proto_goTypes,
		DependencyIndexes: file_irsa_v1_irsa_proto_depIdxs,
		MessageInfos:      file_irsa_v1_irsa_proto_msgTypes,
	}.Build()
	File_irsa_v1_irsa_proto = out.File
	file_irsa_v1_irsa_proto_goTypes = nil
	file_irsa_v1_irsa_proto_depIdxs = nil
}
